// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netby.Infraestucture.Persistence;

#nullable disable

namespace Netby.Infraestucture.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240816195237_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Netby.Domain.Campo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsRequerido")
                        .HasColumnType("bit");

                    b.Property<int>("FormularioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormularioId");

                    b.ToTable("Campos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsRequerido = true,
                            FormularioId = 1,
                            NombreCampo = "Nombre",
                            TipoCampo = "text"
                        },
                        new
                        {
                            Id = 2,
                            EsRequerido = true,
                            FormularioId = 1,
                            NombreCampo = "Fecha de Nacimiento",
                            TipoCampo = "date"
                        },
                        new
                        {
                            Id = 3,
                            EsRequerido = false,
                            FormularioId = 1,
                            NombreCampo = "Estatura",
                            TipoCampo = "number"
                        },
                        new
                        {
                            Id = 4,
                            EsRequerido = true,
                            FormularioId = 2,
                            NombreCampo = "Especie",
                            TipoCampo = "text"
                        },
                        new
                        {
                            Id = 5,
                            EsRequerido = false,
                            FormularioId = 2,
                            NombreCampo = "Raza",
                            TipoCampo = "text"
                        },
                        new
                        {
                            Id = 6,
                            EsRequerido = false,
                            FormularioId = 2,
                            NombreCampo = "Color",
                            TipoCampo = "text"
                        });
                });

            modelBuilder.Entity("Netby.Domain.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formularios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Formulario para ingresar datos básicos de una persona",
                            Nombre = "Datos Personales"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Formulario para ingresar datos de la mascota",
                            Nombre = "Datos de la Mascota"
                        });
                });

            modelBuilder.Entity("Netby.Domain.Campo", b =>
                {
                    b.HasOne("Netby.Domain.Formulario", "Formulario")
                        .WithMany("Campos")
                        .HasForeignKey("FormularioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulario");
                });

            modelBuilder.Entity("Netby.Domain.Formulario", b =>
                {
                    b.Navigation("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
